### PR TITLE
App Metadata  i18n

### PR DESCRIPTION
**Pull request by yurtpage**
Please add the App Metadata to the Weblate.
Here is a sample of Conversations app metadata translation via Weblate https://translate.codeberg.org/projects/conversations/app-store-metadata-conversations/

Meanwhile I added one translation of the full_desscription.txt

### CODE REVIEW

**Comment by yurtpage** [comment]
@pacien sorry for pushing, is anything blocks the merging?

**Comment by pacien** [comment]
Quoting Yurt Page (2024-05-05 11:50:12)
> @pacien sorry for pushing, is anything blocks the merging?

Hi!

Sorry for the delay.

I was concerned about the change of the app's name,
which was named "Tinc App" because it wasn't the only port of Tinc
for Android on the stores at the time.

This no longer seems to be the case,
so I'll go with your proposal ("Tinc Mesh VPN").

I'll go ahead and merge your changes.
I'll also look into adding this to Weblate to ease the translations.

Thank you for your contribution!

**Comment by yurtpage** [comment]
Thank you!

**Comment by yurtpage** [comment]
Donated to you a little bit. Thanks for the app!

**Comment by pacien** [comment]
Quoting Yurt Page (2024-04-17 19:48 CEST):
> Please add the App Metadata to the Weblate.
> Here is a sample of Conversations app metadata translation via Weblate
> https://translate.codeberg.org/projects/conversations/app-store-metadata-conversations/

Sorry for the delay; I've set it up here:
https://translate.codeberg.org/projects/tincapp/

**Comment by yurtpage** [comment]
Than you, I added the link on F-Droid https://gitlab.com/fdroid/fdroiddata/-/merge_requests/19413/diffs

Sadly, I checked and for the last release the metadata translations didn't worked https://f-droid.org/ru/packages/org.pacien.tincapp/

I guess this is because the F-Droid didn't recognized the Tripple-T files.
Can we switch to the more widely used Fastline structure with `/metadata/en-US`?
https://f-droid.org/docs/All_About_Descriptions_Graphics_and_Screenshots

**Comment by yurtpage** [comment]
It also would be great to add the Weblate link to README like "For translations use https://translate.codeberg.org/projects/tincapp/"

**Pull request merged**
